#!/bin/bash

NUM_TESTS=1

# apps=(grep rcount visitor pv clean vhtree collision twitter)
apps=(grep)

# rhos=(0.5 0.7 0.9)
rhos=(0.95)

declare -A series_
series_=([grep]=wcup [rcount]=wcup [visitor]=wcup [pv]=wcup [clean]=wcup [vhtree]=wcup [collision]=adsb [twitter]=tweets)

declare -A models
models=([grep]=model1 [rcount]=model1 [visitor]=model2 [pv]=model2 [clean]=model2 [vhtree]=model2 [collision]=model2 [twitter]=model2)

declare -A pdq_orders
arima_pdqs=([wcup]='(1,0,2)' [tweets]='(1,0,1)' [adsb]='(1,0,3)')

for i in `seq 1 ${NUM_TESTS}` ; do
    for app in ${apps[@]} ; do
        for rho in ${rhos[@]} ; do 
            echo "Running simulation for $app with rho=${rho} ($i/${NUM_TESTS}) ..."

            series=${series_[$app]}
            model=${models[$app]}
            arima_pdq=${arima_pdqs[$series]}

            common_cmd="python src/main.py --sim --app ${app} --rho ${rho} --series ${series} --model ${model} --arima_pdq ${arima_pdq} --num_tests ${NUM_TESTS}"

            ${common_cmd} 
            ${common_cmd} -mua
            ${common_cmd} -mua -fua
            ${common_cmd} -mua -ol -fua
            ${common_cmd} -fem
            ${common_cmd} -fem -mua
            ${common_cmd} -fem -mua -ol
        done
    done
done
